Adding friendly user messages. Running rvm requirements and only installing rvm if brew has been installed. Started function to install common gnu commands I use

diff --git a/script/setup_osx b/script/setup_osx
--- a/script/setup_osx
+++ b/script/setup_osx
@@ -1,19 +1,57 @@
 #!/usr/bin/env bash
 
+DOTFILES_ROOT="`pwd`"
+
+set -e
+
+echo ''
+
+info () {
+  printf "  [ \033[00;34m..\033[0m ] $1"
+}
+
+user () {
+  printf "\r  [ \033[0;33m?\033[0m ] $1 "
+}
+
+success () {
+  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+}
+
+fail () {
+  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+  echo ''
+  exit
+}
+
+
 # install rvm for the current user
 install_rvm () {
     if ! [[ `type -P rvm` ]]; then
-        sh -c '\curl -L https://get.rvm.io | bash -s stable'
+        if [[ `type -P brew` ]]; then
+            info "installing rvm"
+            sh -c '\curl -L https://get.rvm.io | bash -s stable'
+            rvm requirements
+        fi
     fi
 }
 
 # install brew
 install_brew () {
     if ! [[ `type -P brew` ]]; then
+        info "installing brew"
         ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
         brew doctor
     fi
 }
 
-install_rvm
+install_gnu_commands () {
+    if [[ `type -P brew` ]]; then
+        to_install=("wget" "curl" "curl-ca-bundle" "vim" "subversion" "git" "bash" "bash-completion" "nmap" "rsync")
+    else
+        echo 
+    fi
+}
+
 install_brew
+install_rvm
